name: Package Project

# kiedy mam uruchomic automatyzacje
on: [ push ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # pobierz kod
      - uses: actions/checkout@v3
      # moja aplikacja jest w Pythonie
      - name: Set up Python 3
        uses: actions/setup-python@v3
      # instalacja wymaganych bibliotek
      - name: Install deps
        run: make deps
      # testy!!!!!
      - name: Tests
        run: make test
      # LINT!!!
      - name: LINT
        run: make lint
      - name: docker
        run: make docker_run

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.damian969696 }}
          password: ${{ secrets.dckr_pat_xsreBwCi1a8c9Nguw0vNfx1p1Tg }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/app:latest
